version: '3.7'

services:
    #service 1: definition of mysql database
    db:
        image: mysql:8.0.23
        container_name: cooking
        environment:
            - MYSQL_ROOT_PASSWORD=cooking
            - MYSQL_DATABASE=cooking
            - MYSQL_USER=phpmyadmin
            - MYSQL_PASSWORD=cooking
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        networks:
            - common-network

    #service 2: definition of phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: my-php-myadmin
        restart: always

        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_USERNAME: phpmyadmin
            SPRING_DATASOURCE_PASSWORD: cooking

    #service 3: definition of activemq  
    activemq:
        image: webcenter/activemq:latest
        container_name: activemq
        hostname: activemq
        ports:
            - 8161:8161
            - 61613:61613
            - 61616:61616
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data/data/activemq:/data/activemq
            - ./data/var/log/activemq:/var/log/activemq
        environment:
            - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT="true"
            - ACTIVEMQ_ADMIN_LOGIN=admin
            - ACTIVEMQ_ADMIN_PASSWORD=admin
            - ACTIVEMQ_CONFIG_MINMEMORY=512
            - ACTIVEMQ_CONFIG_MAXMEMORY=2048
            - ACTIVEMQ_CONFIG_TOPICS_topic1=hello_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic2=chef_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic3=dish_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic4=ingredient_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic5=recipe_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic6=restaurant_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic7=virtual_topic
            - ACTIVEMQ_CONFIG_QUEUES_queue1=chef_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue2=dish_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue3=ingredient_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue4=recipe_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue5=restaurant_queue
            - ACTIVEMQ_ENABLED_SCHEDULER="true"
            - ACTIVEMQ_MIN_MEMORY=512
            - ACTIVEMQ_MAX_MEMORY=2048
        networks:
            - common-network

    #service 4: definition of your spring-boot app 
    spring-boot:
        image: cooking-app       
        container_name: cooking-app 
        build:
            context: .                         
            dockerfile: Dockerfile              
        ports:
            - "8080:8080"
            - "9900:9900"
        restart: always
        depends_on: 
            - db                               
            - activemq
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cooking?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=FALSE
            SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
#        entrypoint: java
#        command: -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.port=9900 -Dcom.sun.management.jmxremote.rmi.port=9900 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -jar /cooking.jar
        networks:
            - common-network    
        volumes:
            - ./local/dir:/home/var/glowroot
        privileged: true

#Docker Networks
networks:
    common-network:
        name: cooking-app-default
        external: true
        driver: bridge
        
#Volumes
volumes:
    localData:
        driver: local        
   