version: '3.7'

services:
    #service 1: definition of mysql database
    db:
        image: mysql:8.0.23
        container_name: cooking
        environment:
            - MYSQL_ROOT_PASSWORD=cooking
            - MYSQL_DATABASE=cooking
            - MYSQL_USER=phpmyadmin
            - MYSQL_PASSWORD=cooking
        ports:
            - "3306:3306"
        restart: always
        cap_add:
            - SYS_NICE
        networks:
            - common-network

    #service 2: definition of phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: my-php-myadmin
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            SPRING_DATASOURCE_USERNAME: phpmyadmin
            SPRING_DATASOURCE_PASSWORD: cooking
        networks:
            - common-network

    #service 3: definition of CI/CD service  
    jenkins:
        image: jenkins/jenkins:lts
        privileged: true
        user: root
        ports:
            - 8081:8080
            - 50000:50000
        container_name: jenkins
        links:
            - db
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
        networks:
            - common-network

    #service 4: definition of activemq  
    activemq:
        image: webcenter/activemq:latest
        container_name: activemq
        hostname: activemq
        ports:
            - 8161:8161
            - 61613:61613
            - 61616:61616
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./data/data/activemq:/data/activemq
            - ./data/var/log/activemq:/var/log/activemq
        environment:
            - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT="true"
            - ACTIVEMQ_ADMIN_LOGIN=admin
            - ACTIVEMQ_ADMIN_PASSWORD=admin
            - ACTIVEMQ_CONFIG_MINMEMORY=512
            - ACTIVEMQ_CONFIG_MAXMEMORY=2048
            - ACTIVEMQ_CONFIG_TOPICS_topic1=hello_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic2=chef_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic3=dish_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic4=ingredient_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic5=recipe_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic6=restaurant_topic
            - ACTIVEMQ_CONFIG_TOPICS_topic7=virtual_topic
            - ACTIVEMQ_CONFIG_QUEUES_queue1=chef_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue2=dish_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue3=ingredient_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue4=recipe_queue
            - ACTIVEMQ_CONFIG_QUEUES_queue5=restaurant_queue
            - ACTIVEMQ_ENABLED_SCHEDULER="true"
            - ACTIVEMQ_MIN_MEMORY=512
            - ACTIVEMQ_MAX_MEMORY=2048
        networks:
            - common-network

    #service 5: definition of your spring-boot app 
    spring-boot:
        image: cooking-app
        container_name: cooking-app 
        build:
            context: .
            dockerfile: docker/Dockerfile
        ports:
            - "127.0.0.1:8080:8080"
            - "127.0.0.1:4000:4000"
        restart: always
        links:
            - db
        depends_on: 
            - db
            - phpmyadmin
            - activemq
            - jenkins
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cooking?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=FALSE
            SPRING_ACTIVEMQ_BROKER-URL: tcp://activemq:61616
            MYSQL_URL: jdbc:mysql://db:3306/cooking
        networks:
            - common-network    
        privileged: true
#        
#    springboot-app-tests:
#        image: cooking-app
#        command: dockerize -wait tcp://db:3306 -wait tcp://spring-boot:8080 -timeout 10s
#        environment:
#            APP_URL: http://spring-boot:8080
#            APP_DB_HOST: db
#            APP_DB_USER: phpyadmin
#            APP_DB_PASSWORD: cooking
#        networks:
#            - common-network
#        depends_on:
#            - db
#            - spring-boot

#Docker Networks
networks:
    common-network:
        name: cooking-app-default
        external: true
#Volumes
volumes:
    localData:
        driver: local        
   